py_test(
    name = "create_test",
    srcs = ["create_test.py"],
    data = ["//ocijail:ocijail"],
)

py_test(
    name = "exec_test",
    srcs = ["exec_test.py"],
    data = ["//ocijail:ocijail"],
)
